import NextHead from "next/head";

const Head = () => (
  <NextHead>
    <title>SyncNema</title>
    <meta name="description" content="Generated by create-t3-app" />
    <meta name="theme-color" content="#000000" />
    <link rel="icon" href="images/icon.svg" />
  </NextHead>
);

export default Head;
